name: hikingapps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  flutter_map_tile_caching: ^9.0.0
  latlong2: ^0.9.1
  gpx: ^2.2.0
  xml: ^6.5.0
  geolocator: ^11.0.0
  location: ^7.0.0
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gpx/
    - assets/tiles/
